Arrba.Admin/Controllers/BrandsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Arrba.Admin.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Arrba.Domain;
using Arrba.Domain.Models;
using Microsoft.AspNetCore.Authorization;

namespace Arrba.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class BrandsController : Controller
    {
        private readonly DbArrbaContext _context;

        public BrandsController(DbArrbaContext context)
        {
            _context = context;
        }

        // GET: Brands
        public async Task<IActionResult> Index()
        {
            return View(await _context.Brands.ToListAsync());
        }

        // GET: Brands/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _context.Brands
                .FirstOrDefaultAsync(m => m.ID == id);
            if (brand == null)
            {
                return NotFound();
            }

            return View(brand);
        }

        // GET: Brands/Create
        public async Task<IActionResult> Create()
        {
            ViewBag.Categories = new SelectList(await _context.Categories.ToListAsync(), "ID", "Name");

            return View();
        }

        // POST: Brands/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BrandWithCategoryCreate model)
        {
            var categBrand = await _context.CategBrands
                .Include(ct => ct.Brand)
                .Include(ct => ct.Categ)
                .SingleOrDefaultAsync(ct => ct.Brand.Name == model.BrandName && ct.CategID == model.CategoryId);

            var categBrandExsits = categBrand != null;

            if (categBrandExsits)
            {
                ModelState.AddModelError("", $"Brand: '{model.BrandName}' and category '{categBrand.Categ.Name}' already exists");
            }

            if (ModelState.IsValid)
            {
                var category = categBrand?.Categ ?? await _context.Categories.SingleOrDefaultAsync(c => c.ID == model.CategoryId);
                var oldBrand = await _context.Brands.SingleOrDefaultAsync(b => b.Name.Equals(model.BrandName, StringComparison.InvariantCultureIgnoreCase));

                var newBrand = new Brand
                {
                    Name = model.BrandName,
                    Status = model.Status,
                    WatchWeightStatus = model.WatchWeightStatus
                };

                var newCategBrand = new CategBrand
                {
                    Categ = category,
                    Brand = oldBrand ?? newBrand
                };

                _context.Add(newCategBrand);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewBag.Categories = new SelectList(await _context.Categories.ToListAsync(), "ID", "Name");

            return View(model);
        }

        // GET: Brands/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _context.Brands.FindAsync(id);
            if (brand == null)
            {
                return NotFound();
            }
            return View(brand);
        }

        // POST: Brands/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("ID,Name,Status,WatchWeightStatus,LikeValue,LikeCount")] Brand brand)
        {
            if (id != brand.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(brand);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BrandExists(brand.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(brand);
        }

        // GET: Brands/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _context.Brands
                .FirstOrDefaultAsync(m => m.ID == id);
            if (brand == null)
            {
                return NotFound();
            }

            return View(brand);
        }

        // POST: Brands/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var brand = await _context.Brands.FindAsync(id);
            _context.Brands.Remove(brand);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BrandExists(long id)
        {
            return _context.Brands.Any(e => e.ID == id);
        }
    }
}

Arrba.Admin/Controllers/CitiesController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Arrba.Domain;
using Arrba.Domain.Models;
using Arrba.Helpers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Configuration;
using PagedList.Core;

namespace Arrba.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CitiesController : Controller
    {
        private readonly DbArrbaContext _context;
        private readonly int _pageSize;

        public CitiesController(DbArrbaContext context, IConfiguration configuration)
        {
            _context = context;
            _pageSize = configuration.GetValue<int>("PageSize");
        }

        // GET: Cities
        public IActionResult Index(int? page)
        {
            var query = _context.Cities
                .Include(c => c.Country)
                .Include(c => c.Region)
                .OrderBy(c => c.Name);

            var paggedList = new PagedList<City>(query.AsNoTracking(), page ?? 1, _pageSize);

            return View(paggedList);
        }

        // GET: Cities/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var city = await _context.Cities
                .Include(c => c.Region)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (city == null)
            {
                return NotFound();
            }

            return View(city);
        }

        // GET: Cities/Create
        public IActionResult Create()
        {
            ViewData["RegionID"] = new SelectList(_context.Regions, "ID", "Name");
            ViewData["CountryID"] = new SelectList(_context.Countries, "ID", "Name");
            return View();
        }

        // POST: Cities/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,RegionID,CountryID,Name,Alias,Weight,Status,NameMultiLangJson")] City city)
        {
            if (ModelState.IsValid)
            {
                city.Alias = Transliteration.Generate(city.Name);

                _context.Add(city);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["RegionID"] = new SelectList(_context.Regions, "ID", "Name", city.RegionID);
            ViewData["CountryID"] = new SelectList(_context.Countries, "ID", "Name", city.CountryID);
            return View(city);
        }

        // GET: Cities/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var city = await _context.Cities.FindAsync(id);
            if (city == null)
            {
                return NotFound();
            }
            ViewData["RegionID"] = new SelectList(_context.Regions, "ID", "Name", city.RegionID);
            return View(city);
        }

        // POST: Cities/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("ID,RegionID,CountryID,Name,Alias,Weight,Status,NameMultiLangJson")] City city)
        {
            if (id != city.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(city);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CityExists(city.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["RegionID"] = new SelectList(_context.Regions, "ID", "Name", city.RegionID);
            return View(city);
        }

        // GET: Cities/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var city = await _context.Cities
                .Include(c => c.Region)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (city == null)
            {
                return NotFound();
            }

            return View(city);
        }

        // POST: Cities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var city = await _context.Cities.FindAsync(id);
            _context.Cities.Remove(city);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CityExists(long id)
        {
            return _context.Cities.Any(e => e.ID == id);
        }
    }
}

Arrba.Admin/Controllers/UsersController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Arrba.Admin.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Arrba.Domain;
using Arrba.Domain.Models;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Arrba.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly DbArrbaContext _context;
        private readonly IMapper _mapper;

        public UsersController(DbArrbaContext context, UserManager<User> userManager, IMapper mapper)
        {
            _context = context;
            _userManager = userManager;
            _mapper = mapper;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            return View(await _context.Users.ToListAsync());
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult>
            Create([Bind("Email,UserName,UserLastName,Password,PhoneNumber")] UserModelCreate user)
        {
            if (ModelState.IsValid)
            {
                var now = DateTime.Now;
                await _userManager.CreateAsync(new User
                {
                    Email = user.Email,
                    UserName = user.UserName,
                    RegistrationDate = now,
                    LastLogin = now,
                    UserStatus = UserAuthStatus.Authorized
                }, user.Password);

                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            var model = _mapper.Map<UserModelEdit>(user);

            ViewData["RoleId"] = new SelectList(_context.Roles, "Id", "Name");
            return View(model);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("UserId,Email,UserName,UserLastName,Password,PhoneNumber,RoleId")] UserModelEdit model)
        {
            var user = await _context.Users.FindAsync(model.UserId);

            if (user == null) return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    user.UserStatus = model.UserStatus;
                    user.UserName = model.UserName;
                    user.UserLastName = model.UserLastName;
                    user.Email = model.Email;
                    user.PhoneNumber = model.PhoneNumber;

                    _context.Update(user);

                    var userRole = new IdentityUserRole<long>
                    {
                        UserId = model.UserId,
                        RoleId = model.RoleId
                    };

                    var currentRole = await _context.UserRoles.FindAsync(model.UserId, model.RoleId);
                    if (currentRole == null)
                    {
                        await _context.UserRoles.AddAsync(userRole);
                    }
                    else
                    {
                        _context.UserRoles.Update(userRole);
                    }
                    
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(model.UserId))
                    {
                        return NotFound();
                    }

                    throw;
                }
                return RedirectToAction(nameof(Index));
            }

            ViewData["RoleId"] = new SelectList(_context.Roles, "Id", "Name");
            return View(model);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var user = await _context.Users.FindAsync(id);
            _context.Users.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(long id)
        {
            return _context.Users.Any(e => e.Id == id);
        }
    }
}

Arrba.Admin/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Arrba.Admin</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-dark _fixed-top bg-dark navbar-expand-sm">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Admin</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <partial name="_CookieConsentPartial" />
    <div class="container-fluid">
        <div class="row">
            <nav class="col-md-2 d-none d-md-block bg-light">
                <div class="position-sticky sidebar-sticky">

                    @if ((await AuthorizationService.AuthorizeAsync(User, "AdminPolicy")).Succeeded)
                    {
                        await Html.RenderPartialAsync("_MenuPartial");
                    }
                </div>
            </nav>
            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
                <div class="_main-content">
                    @RenderBody()
                </div>
            </main>
        </div>
    </div>


    <footer class="border-top text-light footer bg-dark _fixed-bottom">
        <div class="container-fluid">
            &copy; 2019 - Arrba.Admin - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Arrba.Admin/Views/Shared/_MenuPartial.cshtml
<ul class="nav flex-column list-group list-group-flush">
    <li class="nav-item list-group-item bg-transparent p-0">
        <a class="nav-link text-dark _active" asp-area="" asp-controller="Users" asp-action="Index">
            Пользователи
            <span class="sr-only">(current)</span>
        </a>
    </li>
    <li class="nav-item list-group-item bg-transparent p-0">
        <a class="nav-link text-dark _active" asp-area="" asp-controller="Dealerships" asp-action="Index">
            Дилеры
            <span class="sr-only">(current)</span>
        </a>
    </li>
    <li class="nav-item list-group-item bg-transparent p-0">
        <a class="nav-link text-dark _active" asp-area="" asp-controller="Categories" asp-action="Index">
            Категории
        </a>
    </li>
    <li class="nav-item list-group-item bg-transparent p-0">
        <a class="nav-link text-dark _active" asp-area="" asp-controller="ItemTypes" asp-action="Index">
            Типы
        </a>
    </li>
    <li class="nav-item list-group-item bg-transparent p-0">
        <a class="nav-link text-dark _active" asp-area="" asp-controller="Brands" asp-action="Index">
            Брэнды (марки)
        </a>
    </li>
    <li class="nav-item list-group-item bg-transparent p-0">
        <a class="nav-link text-dark _active" asp-area="" asp-controller="ItemModels" asp-action="Index">
            Модели
        </a>
    </li>
    <li class="nav-item list-group-item bg-transparent p-0">
        <a class="nav-link text-dark _active" asp-area="" asp-controller="Properties" asp-action="Index">
            Properties
        </a>
    </li>
    <li class="nav-item list-group-item bg-transparent p-0">
        <a class="nav-link text-dark _active" asp-area="" asp-controller="Cities" asp-action="Index">
            Cities
        </a>
    </li>
    <li class="nav-item list-group-item bg-transparent p-0">
        <a class="nav-link text-dark _active" asp-area="" asp-controller="CategBrands" asp-action="Index">
            Categories and Brands
        </a>
    </li>
    <li class="nav-item list-group-item bg-transparent p-0">
        <a class="nav-link text-dark _active" asp-area="" asp-controller="PropertyCategs" asp-action="Index">
            Property and item
        </a>
    </li>

    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
        <span>Other</span>
        <a class="d-flex align-items-center text-muted" href="#">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus-circle"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="16"></line><line x1="8" y1="12" x2="16" y2="12"></line></svg>
        </a>
    </h6>
    <li class="nav-item list-group-item bg-transparent p-0">
        <a class="nav-link text-dark _active" asp-area="" asp-controller="AdVehicles" asp-action="Index">
            AdVehicles
        </a>
    </li>
    <li class="nav-item list-group-item bg-transparent p-0">
        <a class="nav-link text-dark _active" asp-area="" asp-controller="AdVehiclesForManager" asp-action="Index">
            AdVehicles for manager
        </a>
    </li>

</ul>